### PR TITLE
merge master into 3.0

### PR DESCRIPTION
**Pull request by ComiR**

### CODE REVIEW

**Comment by ComiR** [comment]
Actually the 3.0 should be the current master (since 3.0.0 isn't released yet). Until the release, master and 3.0 should be kept in sync.
If some of the commits shouldn't be in 3.0.0, we'd have to cherry-pick.

**Comment by kitsunet** [comment]
But then they should've been merged into the 3.0 branch in the first place and upmerged.

**Comment by ComiR** [comment]
I agree, but no other way to change it now ;)

**Comment by kdambekalns** [comment]
Noone noticed the 3.0 existing already, so… An acceptable exception.

**Pull request merged**
