### PR TITLE
TASK: Handle empty default values in `AbstractFinisher`

### PR DESCRIPTION
**Pull request by futape**
Checks if the final value, after resolving `{...}`s, is an empty string
and returns `null`.

### CODE REVIEW

**Comment by bwaidelich** [comment]
@futape Thanks for this contribution!
From reading the code and Commit message I find it quite hard to realize what exactly this change solves though and if it might pose some breaking change. Could you elaborate and/or add a test?

**Comment by futape** [comment]
sorry for the delay.
i opened an issue: #75

**Comment by kdambekalns** [comment]
@bwaidelich ping on this one…

**Comment by bwaidelich** [comment]
Thanks for pinging. I assigned myself and will look into this one asap

**Pull request merged**
