### PR TITLE
[TASK] Allow NULL value for overrideConfiguration

### PR DESCRIPTION
**Pull request by dfeyer**
Migrated from Gerrit: https://review.typo3.org/#/c/40193/

Change-Id: I51b4ad9f2c1e4abed271e7586f4c828137842c1f
Releases: master

### CODE REVIEW

**Comment by dfeyer** [comment]
:+1:

**Comment by dfeyer** [comment]
Required for: https://github.com/neos/neos-development-collection/pull/31

**Comment by hlubek** [comment]
:+1: by reading

**Comment by hlubek** [comment]
:+1: We use it like that in many projects.

The PR should be updated to target the Neos 2.0 branch if it should be included in 2.0.

**Comment by hlubek** [comment]
The PR should be updated to target the Neos 2.0 branch if it should be included in 2.0.

**Comment by hlubek** [comment]
The PR should be updated to target the Neos 2.0 branch if it should be included in 2.0.

**Comment by dfeyer** [comment]
Let's merge only on master this not really a bugfix

**Comment by skurfuerst** [comment]
:1: by reading for master.

**Comment by bwaidelich** [comment]
stumbling upon this almost a year later, this breaks if no $persistenceIdentifier is set because it tries to call
```
$factory->build(NULL, ...)
```

**Comment by dimitriadisg** [comment]
@bwaidelich 
Hello Bastian,

A few more comments on this can be found [here](https://github.com/neos/form/commit/0cac9ef02043c9ae5e25eb41a7f746ba75e80f2d).

I see there is a check in the Form.html template that makes sure that the formIdentifier (persistenceIdentifier) is present, but the problem is still there. However, I don't understand how formIdentifier is populated, I don't see it in fusion or in myForm.yaml configuration. Looks like it fetches the value of 'identifier' from myForm.yaml though.

**Pull request merged**
