### PR TITLE
TASK: Replace preg_replace with PSR-7 UriInterface method for action uri

### LINKED ISSUE #131: FormViewHelper generates empty fragment for action uri due to preg_replace and missing conditino
The current action uri can get a section added (the #[section] value of a uri).

This is done by check if the argument has a value (empty string included) and with preg_replace, the value is added.

Since we get a UriInterface object, we can use the `withFragment` instead, but it requires a stricter check for the section value, since it does not accept a empty string

### PR DESCRIPTION
**Pull request by sorenmalling**
Resolves #131

### CODE REVIEW

**Review by bwaidelich — APPROVED** [review]
Nice one, thanks!

**Comment by Sebobo** [comment]
This seems to be very kaputt. `section` is not set as `$uri->withFragment($this->hasArgument('section'));` does neither update the uri nor set the correct value. 
I'm working on a fix.

**Comment by Sebobo** [comment]
Noticed as I wanted to release but the tests fail.

**Comment by sorenmalling** [comment]
> Noticed as I wanted to release but the tests fail.

What test, where?

**Comment by Sebobo** [comment]
`Neos\Form\Tests\Unit\ViewHelpers\FormViewHelperTest::getFormActionUriTests`

**Pull request merged**
